### ISSUE TITLE
Allow request cancelation

### ISSUE THREAD

**Issue by sarahlensing** [pelias/pelias-android-sdk#56]
### Description
With `okhttp3` we can update `Pelias.java` to return a `Call` object (or a generic wrapper around this object) to allow cancelling a request:
https://square.github.io/okhttp/3.x/okhttp/

**Comment by ecgreb** [comment]
I would rather expose our own public API for request cancellation rather than directly using `Call`. Upgrading OkHttp required a number of changes in the Mapzen SDK. Ideally upgrading this library's inner dependencies would not require changes to the public API nor any apps using it.

**Comment by sarahlensing** [comment]
I prefer that too
